import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile & Settings',
    
    // Profile & Settings Page
    'profile.title': 'Profile & Settings',
    'profile.personalInfo': 'Personal Information',
    'profile.healthProfile': 'Health Profile',
    'profile.notifications': 'Notification Preferences',
    'profile.privacy': 'Privacy Settings',
    'profile.subscription': 'Subscription Management',
    'profile.payments': 'Payment History',
    'profile.appearance': 'Appearance',
    'profile.language': 'Language',
    
    // Personal Information
    'personal.name': 'Name',
    'personal.phone': 'Phone Number',
    'personal.email': 'Email Address',
    'personal.bio': 'Bio',
    'personal.address': 'Address',
    'personal.photo': 'Profile Photo',
    'personal.uploadPhoto': 'Upload Photo',
    'personal.save': 'Save Changes',
    
    // Health Profile
    'health.medicalConditions': 'Medical Conditions',
    'health.injuries': 'Injuries',
    'health.fitnessLevel': 'Fitness Level',
    'health.limitations': 'Physical Limitations',
    'health.beginner': 'Beginner',
    'health.intermediate': 'Intermediate',
    'health.advanced': 'Advanced',
    'health.addCondition': 'Add Condition',
    'health.addInjury': 'Add Injury',
    
    // Notifications
    'notif.email': 'Email Notifications',
    'notif.sessionReminders': 'Session Reminders',
    'notif.achievements': 'Achievement Alerts',
    'notif.workouts': 'Workout Notifications',
    'notif.diet': 'Diet Plan Updates',
    'notif.messages': 'Messages',
    
    // Privacy
    'privacy.showEmail': 'Show Email to Others',
    'privacy.showPhone': 'Show Phone to Others',
    'privacy.showProgress': 'Show Progress to Others',
    'privacy.publicProfile': 'Public Profile',
    
    // Subscription
    'sub.currentPlan': 'Current Plan',
    'sub.price': 'Price',
    'sub.billingCycle': 'Billing Cycle',
    'sub.nextBilling': 'Next Billing Date',
    'sub.features': 'Features',
    'sub.upgradePlan': 'Upgrade Plan',
    'sub.cancelSubscription': 'Cancel Subscription',
    'sub.monthly': 'Monthly',
    
    // Payment History
    'payment.date': 'Date',
    'payment.amount': 'Amount',
    'payment.status': 'Status',
    'payment.invoice': 'Invoice',
    'payment.receipt': 'Receipt',
    'payment.method': 'Payment Method',
    'payment.download': 'Download',
    'payment.noHistory': 'No payment history available',
    
    // Appearance
    'appearance.darkMode': 'Dark Mode',
    'appearance.theme': 'Theme',
    'appearance.light': 'Light',
    'appearance.dark': 'Dark',
    
    // Language
    'lang.select': 'Select Language',
    'lang.english': 'English',
    'lang.hindi': 'Hindi',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.update': 'Update',
    'common.loading': 'Loading...',
    'common.success': 'Success!',
    'common.error': 'Error',
    'common.confirm': 'Confirm',
    
    // Messages
    'msg.profileUpdated': 'Profile updated successfully',
    'msg.settingsSaved': 'Settings saved successfully',
    'msg.error': 'An error occurred. Please try again.',
    
    // Additional Profile Page strings
    'profile.memberSince': 'Member since',
    'profile.editProfile': 'Edit Profile',
    'profile.contactInfo': 'Contact Information',
    'profile.fullName': 'Full Name',
    'profile.bioPlaceholder': 'Tell us about yourself, your fitness goals...',
    'profile.active': 'Active',
    'profile.plan': 'Plan',
    'health.healthProfileDesc': 'Manage your health information and fitness level',
    'health.selectFitnessLevel': 'Select your fitness level',
    'health.medicalPlaceholder': 'List any medical conditions (e.g., diabetes, hypertension...)',
    'health.separateComma': 'Separate multiple conditions with commas',
    'health.injuriesPlaceholder': 'List any injuries or surgeries (e.g., knee injury, back surgery...)',
    'health.separateItems': 'Separate multiple items with commas',
    'health.limitationsPlaceholder': 'Describe any physical limitations or restrictions...',
    'health.saveProfile': 'Save Health Profile',
    'common.saving': 'Saving...',
    'sub.perMonth': '/month',
    'sub.workoutVideos': 'Access to all recorded workout videos',
    'sub.dietManagement': 'Personalized diet management',
    'sub.progressTracking': 'Progress tracking and analytics',
    'sub.changePlan': 'Change Plan',
    'payment.viewReceipts': 'View your invoices and payment receipts',
    'notif.notifPrefs': 'Notification Preferences',
    'notif.emailDesc': 'Receive email updates about your progress',
    'notif.sessionDesc': 'Get notified before live sessions',
    'notif.achievementsDesc': 'Celebrate your milestones',
    'appearance.appearanceTitle': 'Appearance',
    'appearance.appearanceDesc': 'Customize how FitPro looks to you',
    'appearance.darkModeDesc': 'Switch between light and dark themes',
    'lang.languageRegion': 'Language & Region',
    'lang.preferredLanguage': 'Preferred Language',
    'lang.selectLanguage': 'Select language',
    'lang.hindiDisplay': 'हिंदी (Hindi)',
    'lang.englishDisplay': 'English',
    'lang.savePreferences': 'Save Preferences',
    'goals.fitnessGoals': 'Fitness Goals',
    'goals.targetWeight': 'Target Weight (lbs)',
    'goals.weeklyGoal': 'Weekly Workout Goal',
    'goals.updateGoals': 'Update Goals',
    'privacy.privacySettings': 'Privacy Settings',
    'privacy.privacyDesc': 'Control what information is visible to others',
    'privacy.showEmailDesc': 'Allow others to see your email',
    'privacy.showPhoneDesc': 'Allow others to see your phone number',
    'privacy.showProgressDesc': 'Allow trainers to see your workout progress',
    'privacy.savePrivacy': 'Save Privacy Settings',
    'tabs.personal': 'Personal',
    'tabs.health': 'Health',
    'tabs.subscription': 'Subscription',
    'tabs.payments': 'Payments',
    'tabs.preferences': 'Preferences',
    'tabs.privacy': 'Privacy',
    
    // Client Header Navigation
    'nav.training': 'Training',
    'nav.nutrition': 'Nutrition',
    'nav.progressAnalytics': 'Progress & Analytics',
    'nav.liveSessions': 'Live Sessions',
    'nav.workoutHistory': 'Workout History',
    'nav.videoLibrary': 'Video Library',
    'nav.dietMealPlans': 'Diet & Meal Plans',
    'nav.weightTracking': 'Weight Tracking',
    'nav.bodyMeasurements': 'Body Measurements',
    'nav.progressCharts': 'Progress Charts',
    'nav.weeklyCompletion': 'Weekly Completion',
    'nav.achievements': 'Achievements',
    'nav.achievementGallery': 'Achievement Gallery',
    'nav.progressPhotos': 'Progress Photos',
    'nav.personalRecords': 'Personal Records',
    'nav.monthlyReports': 'Monthly Reports',
    'nav.calculator': 'Fitness Calculator',
    'nav.viewProfile': 'View Profile',
    'nav.logout': 'Logout',
    
    // Dashboard Page
    'dash.welcome': 'Welcome back',
    'dash.quickStats': 'Quick Stats',
    'dash.todaysWorkout': 'Today\'s Workout',
    'dash.upcomingSessions': 'Upcoming Sessions',
    'dash.currentGoals': 'Current Goals',
    'dash.recentProgress': 'Recent Progress',
    'dash.noWorkout': 'No workout scheduled for today',
    'dash.browseWorkouts': 'Browse Workouts',
    'dash.noSessions': 'No upcoming sessions',
    'dash.viewAllSessions': 'View All Sessions',
    
    // Workouts Page
    'workout.myWorkouts': 'My Workouts',
    'workout.workoutPlans': 'Workout Plans',
    'workout.exerciseLibrary': 'Exercise Library',
    'workout.currentPlan': 'Current Plan',
    'workout.startWorkout': 'Start Workout',
    'workout.logWorkout': 'Log Workout',
    'workout.viewDetails': 'View Details',
    'workout.completed': 'Completed',
    'workout.inProgress': 'In Progress',
    'workout.duration': 'Duration',
    'workout.exercises': 'Exercises',
    'workout.sets': 'Sets',
    'workout.reps': 'Reps',
    'workout.weight': 'Weight',
    'workout.rest': 'Rest',
    'workout.notes': 'Notes',
    
    // Diet/Nutrition Page
    'diet.mealPlan': 'Meal Plan',
    'diet.todaysMeals': 'Today\'s Meals',
    'diet.waterIntake': 'Water Intake',
    'diet.supplements': 'Supplements',
    'diet.shoppingList': 'Shopping List',
    'diet.mealSchedule': 'Meal Schedule',
    'diet.breakfast': 'Breakfast',
    'diet.lunch': 'Lunch',
    'diet.dinner': 'Dinner',
    'diet.snacks': 'Snacks',
    'diet.calories': 'Calories',
    'diet.protein': 'Protein',
    'diet.carbs': 'Carbs',
    'diet.fats': 'Fats',
    'diet.ingredients': 'Ingredients',
    'diet.instructions': 'Instructions',
    'diet.glasses': 'glasses',
    'diet.goal': 'Goal',
    'diet.dosage': 'Dosage',
    'diet.timing': 'Timing',
    
    // Sessions Page
    'session.liveSessions': 'Live Sessions',
    'session.upcoming': 'Upcoming',
    'session.past': 'Past',
    'session.joinSession': 'Join Session',
    'session.scheduled': 'Scheduled',
    'session.completed': 'Completed',
    'session.cancelled': 'Cancelled',
    'session.with': 'with',
    'session.duration': 'Duration',
    'session.sessionType': 'Session Type',
    'session.mins': 'mins',
    
    // Goals Page
    'goals.title': 'My Goals',
    'goals.createGoal': 'Create Goal',
    'goals.editGoal': 'Edit Goal',
    'goals.deleteGoal': 'Delete Goal',
    'goals.goalType': 'Goal Type',
    'goals.weight': 'Weight',
    'goals.fitness': 'Fitness',
    'goals.nutrition': 'Nutrition',
    'goals.goalTitle': 'Title',
    'goals.description': 'Description',
    'goals.targetValue': 'Target Value',
    'goals.currentValue': 'Current Value',
    'goals.unit': 'Unit',
    'goals.targetDate': 'Target Date',
    'goals.progress': 'Progress',
    'goals.active': 'Active',
    'goals.completed': 'Completed',
    'goals.abandoned': 'Abandoned',
    'goals.milestone': 'Milestone',
    'goals.achieved': 'Achieved',
    
    // Weight Tracking
    'weight.title': 'Weight Tracking',
    'weight.currentWeight': 'Current Weight',
    'weight.targetWeight': 'Target Weight',
    'weight.progress': 'Progress',
    'weight.addEntry': 'Add Entry',
    'weight.date': 'Date',
    'weight.weight': 'Weight',
    'weight.change': 'Change',
    'weight.history': 'Weight History',
    'weight.trend': 'Trend',
    
    // Body Measurements
    'measure.title': 'Body Measurements',
    'measure.addMeasurement': 'Add Measurement',
    'measure.chest': 'Chest',
    'measure.waist': 'Waist',
    'measure.hips': 'Hips',
    'measure.thighs': 'Thighs',
    'measure.arms': 'Arms',
    'measure.calves': 'Calves',
    'measure.neck': 'Neck',
    'measure.shoulders': 'Shoulders',
    
    // Progress Charts
    'progress.title': 'Progress Charts',
    'progress.weightProgress': 'Weight Progress',
    'progress.measurementProgress': 'Measurement Progress',
    'progress.workoutProgress': 'Workout Progress',
    'progress.strengthProgress': 'Strength Progress',
    'progress.timePeriod': 'Time Period',
    'progress.week': 'Week',
    'progress.month': 'Month',
    'progress.year': 'Year',
    'progress.all': 'All Time',
    
    // Achievements
    'achieve.title': 'Achievements',
    'achieve.earned': 'Earned',
    'achieve.locked': 'Locked',
    'achieve.unlocked': 'Unlocked',
    'achieve.earnedOn': 'Earned on',
    'achieve.milestone': 'Milestone',
    'achieve.badge': 'Badge',
    
    // Personal Records
    'records.title': 'Personal Records',
    'records.exercise': 'Exercise',
    'records.record': 'Record',
    'records.date': 'Date',
    'records.addRecord': 'Add Record',
    'records.updateRecord': 'Update Record',
    
    // Monthly Reports
    'reports.title': 'Monthly Reports',
    'reports.month': 'Month',
    'reports.workoutsCompleted': 'Workouts Completed',
    'reports.totalDuration': 'Total Duration',
    'reports.avgHeartRate': 'Avg Heart Rate',
    'reports.caloriesBurned': 'Calories Burned',
    'reports.downloadReport': 'Download Report',
    
    // Weekly Completion
    'weekly.title': 'Weekly Completion',
    'weekly.thisWeek': 'This Week',
    'weekly.completionRate': 'Completion Rate',
    'weekly.workoutsCompleted': 'Workouts Completed',
    'weekly.goalCompletion': 'Goal Completion',
    
    // Video Library
    'video.library': 'Video Library',
    'video.category': 'Category',
    'video.duration': 'Duration',
    'video.difficulty': 'Difficulty',
    'video.watchVideo': 'Watch Video',
    'video.allCategories': 'All Categories',
    'video.beginner': 'Beginner',
    'video.intermediate': 'Intermediate',
    'video.advanced': 'Advanced',
    
    // History
    'history.title': 'History',
    'history.workoutHistory': 'Workout History',
    'history.sessionHistory': 'Session History',
    'history.viewDetails': 'View Details',
    'history.noHistory': 'No history available',
    
    // Client Access/Login
    'access.title': 'Client Access',
    'access.welcome': 'Welcome to FitPro',
    'access.enterPhone': 'Enter your phone number to access your personalized fitness dashboard',
    'access.phoneNumber': 'Phone Number',
    'access.fullName': 'Full Name',
    'access.submit': 'Access Dashboard',
    'access.invalidPhone': 'Invalid phone number',
    'access.clientNotFound': 'Client not found',
    
    // Communication - Messages
    'comm.messages': 'Messages',
    'comm.trainerMessaging': 'Trainer Messaging',
    'comm.newMessage': 'New Message',
    'comm.sendMessage': 'Send Message',
    'comm.typeMessage': 'Type your message...',
    'comm.conversations': 'Conversations',
    'comm.noConversations': 'No conversations yet',
    'comm.unreadMessages': 'Unread Messages',
    'comm.messageTrainer': 'Message Your Trainer',
    'comm.onlineNow': 'Online Now',
    'comm.lastSeen': 'Last seen',
    'comm.typing': 'Typing...',
    
    // Communication - Support Tickets
    'comm.support': 'Support',
    'comm.supportTickets': 'Support Tickets',
    'comm.createTicket': 'Create Ticket',
    'comm.newTicket': 'New Support Ticket',
    'comm.ticketSubject': 'Subject',
    'comm.ticketCategory': 'Category',
    'comm.ticketPriority': 'Priority',
    'comm.ticketDescription': 'Description',
    'comm.ticketNumber': 'Ticket #',
    'comm.ticketStatus': 'Status',
    'comm.ticketOpen': 'Open',
    'comm.ticketInProgress': 'In Progress',
    'comm.ticketResolved': 'Resolved',
    'comm.ticketClosed': 'Closed',
    'comm.statusOpen': 'Open',
    'comm.statusInProgress': 'In Progress',
    'comm.statusWaitingResponse': 'Waiting for Response',
    'comm.statusResolved': 'Resolved',
    'comm.statusClosed': 'Closed',
    'comm.priorityLow': 'Low',
    'comm.priorityMedium': 'Medium',
    'comm.priorityHigh': 'High',
    'comm.priorityUrgent': 'Urgent',
    'comm.categoryGeneral': 'General',
    'comm.categoryTechnical': 'Technical',
    'comm.categoryBilling': 'Billing',
    'comm.categoryAccount': 'Account',
    'comm.categoryTraining': 'Training',
    'comm.categoryWorkout': 'Workout',
    'comm.categoryDiet': 'Diet',
    'comm.noTickets': 'No support tickets yet',
    'comm.viewTicket': 'View Ticket',
    'comm.addResponse': 'Add Response',
    'comm.yourResponse': 'Your response...',
    'comm.submitTicket': 'Submit Ticket',
    
    // Communication - Announcements
    'comm.announcements': 'Announcements',
    'comm.announcementFeed': 'Announcement Feed',
    'comm.newAnnouncement': 'New Announcement',
    'comm.noAnnouncements': 'No announcements yet',
    'comm.pinned': 'Pinned',
    'comm.urgent': 'Urgent',
    'comm.important': 'Important',
    'comm.info': 'Info',
    'comm.viewAll': 'View All',
    'comm.readMore': 'Read More',
    'comm.postedBy': 'Posted by',
    'comm.postedOn': 'Posted on',
    
    // Communication - Community Forum
    'comm.forum': 'Forum',
    'comm.communityForum': 'Community Forum',
    'comm.newTopic': 'New Topic',
    'comm.createTopic': 'Create Topic',
    'comm.topicTitle': 'Topic Title',
    'comm.topicCategory': 'Category',
    'comm.topicContent': 'Content',
    'comm.postTopic': 'Post Topic',
    'comm.noTopics': 'No forum topics yet',
    'comm.replies': 'Replies',
    'comm.views': 'Views',
    'comm.lastActivity': 'Last Activity',
    'comm.addReply': 'Add Reply',
    'comm.postReply': 'Post Reply',
    'comm.yourReply': 'Your reply...',
    'comm.like': 'Like',
    'comm.liked': 'Liked',
    'comm.categoryWorkoutTips': 'Workout Tips',
    'comm.categoryNutrition': 'Nutrition',
    'comm.categorySuccess': 'Success Stories',
    'comm.categoryQuestions': 'Questions',
    'comm.categoryGeneralDiscussion': 'General Discussion',
    'comm.startedBy': 'Started by',
    'comm.replyBy': 'Reply by',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.profile': 'प्रोफाइल और सेटिंग्स',
    
    // Profile & Settings Page
    'profile.title': 'प्रोफाइल और सेटिंग्स',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.healthProfile': 'स्वास्थ्य प्रोफाइल',
    'profile.notifications': 'सूचना प्राथमिकताएं',
    'profile.privacy': 'गोपनीयता सेटिंग्स',
    'profile.subscription': 'सदस्यता प्रबंधन',
    'profile.payments': 'भुगतान इतिहास',
    'profile.appearance': 'दिखावट',
    'profile.language': 'भाषा',
    
    // Personal Information
    'personal.name': 'नाम',
    'personal.phone': 'फोन नंबर',
    'personal.email': 'ईमेल पता',
    'personal.bio': 'बायो',
    'personal.address': 'पता',
    'personal.photo': 'प्रोफाइल फोटो',
    'personal.uploadPhoto': 'फोटो अपलोड करें',
    'personal.save': 'परिवर्तन सहेजें',
    
    // Health Profile
    'health.medicalConditions': 'चिकित्सा स्थितियां',
    'health.injuries': 'चोटें',
    'health.fitnessLevel': 'फिटनेस स्तर',
    'health.limitations': 'शारीरिक सीमाएं',
    'health.beginner': 'शुरुआती',
    'health.intermediate': 'मध्यवर्ती',
    'health.advanced': 'उन्नत',
    'health.addCondition': 'स्थिति जोड़ें',
    'health.addInjury': 'चोट जोड़ें',
    
    // Notifications
    'notif.email': 'ईमेल सूचनाएं',
    'notif.sessionReminders': 'सत्र अनुस्मारक',
    'notif.achievements': 'उपलब्धि अलर्ट',
    'notif.workouts': 'वर्कआउट सूचनाएं',
    'notif.diet': 'आहार योजना अपडेट',
    'notif.messages': 'संदेश',
    
    // Privacy
    'privacy.showEmail': 'दूसरों को ईमेल दिखाएं',
    'privacy.showPhone': 'दूसरों को फोन दिखाएं',
    'privacy.showProgress': 'दूसरों को प्रगति दिखाएं',
    'privacy.publicProfile': 'सार्वजनिक प्रोफाइल',
    
    // Subscription
    'sub.currentPlan': 'वर्तमान योजना',
    'sub.price': 'कीमत',
    'sub.billingCycle': 'बिलिंग चक्र',
    'sub.nextBilling': 'अगली बिलिंग तारीख',
    'sub.features': 'विशेषताएं',
    'sub.upgradePlan': 'योजना अपग्रेड करें',
    'sub.cancelSubscription': 'सदस्यता रद्द करें',
    'sub.monthly': 'मासिक',
    
    // Payment History
    'payment.date': 'तारीख',
    'payment.amount': 'राशि',
    'payment.status': 'स्थिति',
    'payment.invoice': 'चालान',
    'payment.receipt': 'रसीद',
    'payment.method': 'भुगतान विधि',
    'payment.download': 'डाउनलोड',
    'payment.noHistory': 'कोई भुगतान इतिहास उपलब्ध नहीं',
    
    // Appearance
    'appearance.darkMode': 'डार्क मोड',
    'appearance.theme': 'थीम',
    'appearance.light': 'लाइट',
    'appearance.dark': 'डार्क',
    
    // Language
    'lang.select': 'भाषा चुनें',
    'lang.english': 'अंग्रेज़ी',
    'lang.hindi': 'हिंदी',
    
    // Common
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.add': 'जोड़ें',
    'common.update': 'अपडेट करें',
    'common.loading': 'लोड हो रहा है...',
    'common.success': 'सफलता!',
    'common.error': 'त्रुटि',
    'common.confirm': 'पुष्टि करें',
    
    // Messages
    'msg.profileUpdated': 'प्रोफाइल सफलतापूर्वक अपडेट हुआ',
    'msg.settingsSaved': 'सेटिंग्स सफलतापूर्वक सहेजी गईं',
    'msg.error': 'एक त्रुटि हुई। कृपया पुनः प्रयास करें।',
    
    // Additional Profile Page strings
    'profile.memberSince': 'सदस्य बने',
    'profile.editProfile': 'प्रोफाइल संपादित करें',
    'profile.contactInfo': 'संपर्क जानकारी',
    'profile.fullName': 'पूरा नाम',
    'profile.bioPlaceholder': 'अपने बारे में बताएं, अपने फिटनेस लक्ष्य...',
    'profile.active': 'सक्रिय',
    'profile.plan': 'योजना',
    'health.healthProfileDesc': 'अपनी स्वास्थ्य जानकारी और फिटनेस स्तर प्रबंधित करें',
    'health.selectFitnessLevel': 'अपना फिटनेस स्तर चुनें',
    'health.medicalPlaceholder': 'कोई चिकित्सा स्थिति बताएं (जैसे, मधुमेह, उच्च रक्तचाप...)',
    'health.separateComma': 'अनेक स्थितियों को अल्पविराम से अलग करें',
    'health.injuriesPlaceholder': 'कोई चोट या सर्जरी बताएं (जैसे, घुटने की चोट, पीठ की सर्जरी...)',
    'health.separateItems': 'अनेक वस्तुओं को अल्पविराम से अलग करें',
    'health.limitationsPlaceholder': 'कोई शारीरिक सीमाएं या प्रतिबंध बताएं...',
    'health.saveProfile': 'स्वास्थ्य प्रोफाइल सहेजें',
    'common.saving': 'सहेज रहे हैं...',
    'sub.perMonth': '/महीना',
    'sub.workoutVideos': 'सभी रिकॉर्ड किए गए वर्कआउट वीडियो तक पहुंच',
    'sub.dietManagement': 'व्यक्तिगत आहार प्रबंधन',
    'sub.progressTracking': 'प्रगति ट्रैकिंग और विश्लेषण',
    'sub.changePlan': 'योजना बदलें',
    'payment.viewReceipts': 'अपने बिल और भुगतान रसीदें देखें',
    'notif.notifPrefs': 'सूचना प्राथमिकताएं',
    'notif.emailDesc': 'अपनी प्रगति के बारे में ईमेल अपडेट प्राप्त करें',
    'notif.sessionDesc': 'लाइव सत्र से पहले सूचना प्राप्त करें',
    'notif.achievementsDesc': 'अपनी उपलब्धियां मनाएं',
    'appearance.appearanceTitle': 'स्वरूप',
    'appearance.appearanceDesc': 'FitPro का स्वरूप अनुकूलित करें',
    'appearance.darkModeDesc': 'लाइट और डार्क थीम के बीच स्विच करें',
    'lang.languageRegion': 'भाषा और क्षेत्र',
    'lang.preferredLanguage': 'पसंदीदा भाषा',
    'lang.selectLanguage': 'भाषा चुनें',
    'lang.hindiDisplay': 'हिंदी (Hindi)',
    'lang.englishDisplay': 'English',
    'lang.savePreferences': 'प्राथमिकताएं सहेजें',
    'goals.fitnessGoals': 'फिटनेस लक्ष्य',
    'goals.targetWeight': 'लक्षित वजन (पाउंड)',
    'goals.weeklyGoal': 'साप्ताहिक वर्कआउट लक्ष्य',
    'goals.updateGoals': 'लक्ष्य अपडेट करें',
    'privacy.privacySettings': 'गोपनीयता सेटिंग्स',
    'privacy.privacyDesc': 'दूसरों को कौन सी जानकारी दिखाई देगी, नियंत्रित करें',
    'privacy.showEmailDesc': 'दूसरों को आपका ईमेल देखने दें',
    'privacy.showPhoneDesc': 'दूसरों को आपका फ़ोन नंबर देखने दें',
    'privacy.showProgressDesc': 'प्रशिक्षकों को अपनी वर्कआउट प्रगति देखने दें',
    'privacy.savePrivacy': 'गोपनीयता सेटिंग्स सहेजें',
    'tabs.personal': 'व्यक्तिगत',
    'tabs.health': 'स्वास्थ्य',
    'tabs.subscription': 'सदस्यता',
    'tabs.payments': 'भुगतान',
    'tabs.preferences': 'प्राथमिकताएं',
    'tabs.privacy': 'गोपनीयता',
    
    // Client Header Navigation
    'nav.training': 'प्रशिक्षण',
    'nav.nutrition': 'पोषण',
    'nav.progressAnalytics': 'प्रगति और विश्लेषण',
    'nav.liveSessions': 'लाइव सत्र',
    'nav.workoutHistory': 'वर्कआउट इतिहास',
    'nav.videoLibrary': 'वीडियो लाइब्रेरी',
    'nav.dietMealPlans': 'आहार और भोजन योजना',
    'nav.weightTracking': 'वजन ट्रैकिंग',
    'nav.bodyMeasurements': 'शरीर माप',
    'nav.progressCharts': 'प्रगति चार्ट',
    'nav.weeklyCompletion': 'साप्ताहिक पूर्णता',
    'nav.achievements': 'उपलब्धियां',
    'nav.achievementGallery': 'उपलब्धि गैलरी',
    'nav.progressPhotos': 'प्रगति फोटो',
    'nav.personalRecords': 'व्यक्तिगत रिकॉर्ड',
    'nav.monthlyReports': 'मासिक रिपोर्ट',
    'nav.calculator': 'फिटनेस कैलकुलेटर',
    'nav.viewProfile': 'प्रोफाइल देखें',
    'nav.logout': 'लॉगआउट',
    
    // Dashboard Page
    'dash.welcome': 'वापस स्वागत है',
    'dash.quickStats': 'त्वरित आंकड़े',
    'dash.todaysWorkout': 'आज का वर्कआउट',
    'dash.upcomingSessions': 'आगामी सत्र',
    'dash.currentGoals': 'वर्तमान लक्ष्य',
    'dash.recentProgress': 'हाल की प्रगति',
    'dash.noWorkout': 'आज के लिए कोई वर्कआउट निर्धारित नहीं',
    'dash.browseWorkouts': 'वर्कआउट ब्राउज़ करें',
    'dash.noSessions': 'कोई आगामी सत्र नहीं',
    'dash.viewAllSessions': 'सभी सत्र देखें',
    
    // Workouts Page
    'workout.myWorkouts': 'मेरे वर्कआउट',
    'workout.workoutPlans': 'वर्कआउट योजनाएं',
    'workout.exerciseLibrary': 'व्यायाम लाइब्रेरी',
    'workout.currentPlan': 'वर्तमान योजना',
    'workout.startWorkout': 'वर्कआउट शुरू करें',
    'workout.logWorkout': 'वर्कआउट लॉग करें',
    'workout.viewDetails': 'विवरण देखें',
    'workout.completed': 'पूर्ण',
    'workout.inProgress': 'प्रगति में',
    'workout.duration': 'अवधि',
    'workout.exercises': 'व्यायाम',
    'workout.sets': 'सेट',
    'workout.reps': 'रिप्स',
    'workout.weight': 'वजन',
    'workout.rest': 'आराम',
    'workout.notes': 'नोट्स',
    
    // Diet/Nutrition Page
    'diet.mealPlan': 'भोजन योजना',
    'diet.todaysMeals': 'आज के भोजन',
    'diet.waterIntake': 'पानी का सेवन',
    'diet.supplements': 'सप्लीमेंट',
    'diet.shoppingList': 'खरीदारी सूची',
    'diet.mealSchedule': 'भोजन समय-सारणी',
    'diet.breakfast': 'नाश्ता',
    'diet.lunch': 'दोपहर का भोजन',
    'diet.dinner': 'रात का भोजन',
    'diet.snacks': 'स्नैक्स',
    'diet.calories': 'कैलोरी',
    'diet.protein': 'प्रोटीन',
    'diet.carbs': 'कार्ब्स',
    'diet.fats': 'वसा',
    'diet.ingredients': 'सामग्री',
    'diet.instructions': 'निर्देश',
    'diet.glasses': 'गिलास',
    'diet.goal': 'लक्ष्य',
    'diet.dosage': 'खुराक',
    'diet.timing': 'समय',
    
    // Sessions Page
    'session.liveSessions': 'लाइव सत्र',
    'session.upcoming': 'आगामी',
    'session.past': 'पिछले',
    'session.joinSession': 'सत्र में शामिल हों',
    'session.scheduled': 'निर्धारित',
    'session.completed': 'पूर्ण',
    'session.cancelled': 'रद्द',
    'session.with': 'के साथ',
    'session.duration': 'अवधि',
    'session.sessionType': 'सत्र प्रकार',
    'session.mins': 'मिनट',
    
    // Goals Page
    'goals.title': 'मेरे लक्ष्य',
    'goals.createGoal': 'लक्ष्य बनाएं',
    'goals.editGoal': 'लक्ष्य संपादित करें',
    'goals.deleteGoal': 'लक्ष्य हटाएं',
    'goals.goalType': 'लक्ष्य प्रकार',
    'goals.weight': 'वजन',
    'goals.fitness': 'फिटनेस',
    'goals.nutrition': 'पोषण',
    'goals.goalTitle': 'शीर्षक',
    'goals.description': 'विवरण',
    'goals.targetValue': 'लक्ष्य मान',
    'goals.currentValue': 'वर्तमान मान',
    'goals.unit': 'इकाई',
    'goals.targetDate': 'लक्ष्य तारीख',
    'goals.progress': 'प्रगति',
    'goals.active': 'सक्रिय',
    'goals.completed': 'पूर्ण',
    'goals.abandoned': 'त्यागा हुआ',
    'goals.milestone': 'मील का पत्थर',
    'goals.achieved': 'हासिल किया',
    
    // Weight Tracking
    'weight.title': 'वजन ट्रैकिंग',
    'weight.currentWeight': 'वर्तमान वजन',
    'weight.targetWeight': 'लक्षित वजन',
    'weight.progress': 'प्रगति',
    'weight.addEntry': 'प्रविष्टि जोड़ें',
    'weight.date': 'तारीख',
    'weight.weight': 'वजन',
    'weight.change': 'परिवर्तन',
    'weight.history': 'वजन इतिहास',
    'weight.trend': 'ट्रेंड',
    
    // Body Measurements
    'measure.title': 'शरीर माप',
    'measure.addMeasurement': 'माप जोड़ें',
    'measure.chest': 'छाती',
    'measure.waist': 'कमर',
    'measure.hips': 'कूल्हे',
    'measure.thighs': 'जांघें',
    'measure.arms': 'बाहें',
    'measure.calves': 'पिंडलियां',
    'measure.neck': 'गर्दन',
    'measure.shoulders': 'कंधे',
    
    // Progress Charts
    'progress.title': 'प्रगति चार्ट',
    'progress.weightProgress': 'वजन प्रगति',
    'progress.measurementProgress': 'माप प्रगति',
    'progress.workoutProgress': 'वर्कआउट प्रगति',
    'progress.strengthProgress': 'शक्ति प्रगति',
    'progress.timePeriod': 'समय अवधि',
    'progress.week': 'सप्ताह',
    'progress.month': 'महीना',
    'progress.year': 'वर्ष',
    'progress.all': 'सभी समय',
    
    // Achievements
    'achieve.title': 'उपलब्धियां',
    'achieve.earned': 'अर्जित',
    'achieve.locked': 'लॉक',
    'achieve.unlocked': 'अनलॉक',
    'achieve.earnedOn': 'प्राप्त किया',
    'achieve.milestone': 'मील का पत्थर',
    'achieve.badge': 'बैज',
    
    // Personal Records
    'records.title': 'व्यक्तिगत रिकॉर्ड',
    'records.exercise': 'व्यायाम',
    'records.record': 'रिकॉर्ड',
    'records.date': 'तारीख',
    'records.addRecord': 'रिकॉर्ड जोड़ें',
    'records.updateRecord': 'रिकॉर्ड अपडेट करें',
    
    // Monthly Reports
    'reports.title': 'मासिक रिपोर्ट',
    'reports.month': 'महीना',
    'reports.workoutsCompleted': 'पूर्ण किए गए वर्कआउट',
    'reports.totalDuration': 'कुल अवधि',
    'reports.avgHeartRate': 'औसत हृदय गति',
    'reports.caloriesBurned': 'कैलोरी बर्न',
    'reports.downloadReport': 'रिपोर्ट डाउनलोड करें',
    
    // Weekly Completion
    'weekly.title': 'साप्ताहिक पूर्णता',
    'weekly.thisWeek': 'इस सप्ताह',
    'weekly.completionRate': 'पूर्णता दर',
    'weekly.workoutsCompleted': 'पूर्ण किए गए वर्कआउट',
    'weekly.goalCompletion': 'लक्ष्य पूर्णता',
    
    // Video Library
    'video.library': 'वीडियो लाइब्रेरी',
    'video.category': 'श्रेणी',
    'video.duration': 'अवधि',
    'video.difficulty': 'कठिनाई',
    'video.watchVideo': 'वीडियो देखें',
    'video.allCategories': 'सभी श्रेणियां',
    'video.beginner': 'शुरुआती',
    'video.intermediate': 'मध्यवर्ती',
    'video.advanced': 'उन्नत',
    
    // History
    'history.title': 'इतिहास',
    'history.workoutHistory': 'वर्कआउट इतिहास',
    'history.sessionHistory': 'सत्र इतिहास',
    'history.viewDetails': 'विवरण देखें',
    'history.noHistory': 'कोई इतिहास उपलब्ध नहीं',
    
    // Client Access/Login
    'access.title': 'क्लाइंट एक्सेस',
    'access.welcome': 'FitPro में आपका स्वागत है',
    'access.enterPhone': 'अपने व्यक्तिगत फिटनेस डैशबोर्ड तक पहुंचने के लिए अपना फोन नंबर दर्ज करें',
    'access.phoneNumber': 'फोन नंबर',
    'access.fullName': 'पूरा नाम',
    'access.submit': 'डैशबोर्ड एक्सेस करें',
    'access.invalidPhone': 'अमान्य फोन नंबर',
    'access.clientNotFound': 'क्लाइंट नहीं मिला',
    
    // Communication - Messages
    'comm.messages': 'संदेश',
    'comm.trainerMessaging': 'ट्रेनर मैसेजिंग',
    'comm.newMessage': 'नया संदेश',
    'comm.sendMessage': 'संदेश भेजें',
    'comm.typeMessage': 'अपना संदेश टाइप करें...',
    'comm.conversations': 'वार्तालाप',
    'comm.noConversations': 'अभी तक कोई वार्तालाप नहीं',
    'comm.unreadMessages': 'अपठित संदेश',
    'comm.messageTrainer': 'अपने ट्रेनर को संदेश भेजें',
    'comm.onlineNow': 'अभी ऑनलाइन',
    'comm.lastSeen': 'अंतिम बार देखा गया',
    'comm.typing': 'टाइप कर रहे हैं...',
    
    // Communication - Support Tickets
    'comm.support': 'सहायता',
    'comm.supportTickets': 'सहायता टिकट',
    'comm.createTicket': 'टिकट बनाएं',
    'comm.newTicket': 'नया सहायता टिकट',
    'comm.ticketSubject': 'विषय',
    'comm.ticketCategory': 'श्रेणी',
    'comm.ticketPriority': 'प्राथमिकता',
    'comm.ticketDescription': 'विवरण',
    'comm.ticketNumber': 'टिकट #',
    'comm.ticketStatus': 'स्थिति',
    'comm.ticketOpen': 'खुला',
    'comm.ticketInProgress': 'प्रगति में',
    'comm.ticketResolved': 'हल हो गया',
    'comm.ticketClosed': 'बंद',
    'comm.statusOpen': 'खुला',
    'comm.statusInProgress': 'प्रगति में',
    'comm.statusWaitingResponse': 'प्रतिक्रिया की प्रतीक्षा',
    'comm.statusResolved': 'हल हो गया',
    'comm.statusClosed': 'बंद',
    'comm.priorityLow': 'कम',
    'comm.priorityMedium': 'मध्यम',
    'comm.priorityHigh': 'उच्च',
    'comm.priorityUrgent': 'तत्काल',
    'comm.categoryGeneral': 'सामान्य',
    'comm.categoryTechnical': 'तकनीकी',
    'comm.categoryBilling': 'बिलिंग',
    'comm.categoryAccount': 'खाता',
    'comm.categoryTraining': 'प्रशिक्षण',
    'comm.categoryWorkout': 'वर्कआउट',
    'comm.categoryDiet': 'आहार',
    'comm.noTickets': 'अभी तक कोई सहायता टिकट नहीं',
    'comm.viewTicket': 'टिकट देखें',
    'comm.addResponse': 'प्रतिक्रिया जोड़ें',
    'comm.yourResponse': 'आपकी प्रतिक्रिया...',
    'comm.submitTicket': 'टिकट सबमिट करें',
    
    // Communication - Announcements
    'comm.announcements': 'घोषणाएं',
    'comm.announcementFeed': 'घोषणा फ़ीड',
    'comm.newAnnouncement': 'नई घोषणा',
    'comm.noAnnouncements': 'अभी तक कोई घोषणा नहीं',
    'comm.pinned': 'पिन किया गया',
    'comm.urgent': 'तत्काल',
    'comm.important': 'महत्वपूर्ण',
    'comm.info': 'जानकारी',
    'comm.viewAll': 'सभी देखें',
    'comm.readMore': 'और पढ़ें',
    'comm.postedBy': 'द्वारा पोस्ट किया गया',
    'comm.postedOn': 'को पोस्ट किया गया',
    
    // Communication - Community Forum
    'comm.forum': 'मंच',
    'comm.communityForum': 'समुदाय मंच',
    'comm.newTopic': 'नया विषय',
    'comm.createTopic': 'विषय बनाएं',
    'comm.topicTitle': 'विषय शीर्षक',
    'comm.topicCategory': 'श्रेणी',
    'comm.topicContent': 'सामग्री',
    'comm.postTopic': 'विषय पोस्ट करें',
    'comm.noTopics': 'अभी तक कोई मंच विषय नहीं',
    'comm.replies': 'उत्तर',
    'comm.views': 'दृश्य',
    'comm.lastActivity': 'अंतिम गतिविधि',
    'comm.addReply': 'उत्तर जोड़ें',
    'comm.postReply': 'उत्तर पोस्ट करें',
    'comm.yourReply': 'आपका उत्तर...',
    'comm.like': 'पसंद',
    'comm.liked': 'पसंद किया',
    'comm.categoryWorkoutTips': 'वर्कआउट टिप्स',
    'comm.categoryNutrition': 'पोषण',
    'comm.categorySuccess': 'सफलता की कहानियां',
    'comm.categoryQuestions': 'प्रश्न',
    'comm.categoryGeneralDiscussion': 'सामान्य चर्चा',
    'comm.startedBy': 'द्वारा शुरू किया गया',
    'comm.replyBy': 'द्वारा उत्तर दिया गया',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('fitpro-language');
    return (stored === 'hi' || stored === 'en') ? stored : 'en';
  });

  useEffect(() => {
    localStorage.setItem('fitpro-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
